import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("parent/dashboard", "routes/parent.dashboard.tsx"),
  route("m/parent/dashboard", "routes/m.parent.dashboard.tsx"),
  route("m/parent/status", "routes/mobile-parent/m.parent.status.tsx"),
  route("m/parent/profil-ibu", "routes/mobile-parent/m.parent.profil-ibu.tsx"),
  route("m/parent/anak", "routes/mobile-parent/m.parent.anak.tsx"),
  route("m/parent/informasi", "routes/mobile-parent/m.parent.informasi.tsx"),
  route("m/parent/anak/new", "routes/m.parent.anak.new.tsx"),
  route("m/parent/anak/:anakId", "routes/m.parent.anak.$anakId.tsx"),
  route("m/parent/anak/:anakId/profil", "routes/m.parent.anak.$anakId.profil.tsx"),
  route("m/parent/anak/:anakId/pertumbuhan/new", "routes/m.parent.anak.$anakId.pertumbuhan.new.tsx"),
  route("m/parent/anak/:anakId/imunisasi/new", "routes/m.parent.anak.$anakId.imunisasi.new.tsx"),
  route("cadre/dashboard", "routes/cadre.dashboard.tsx"),
  route("m/cadre/dashboard", "routes/mobile-cadre/m.cadre.dashboard.tsx"),
  route("m/cadre/anak", "routes/mobile-cadre/m.cadre.anak.tsx"),
  route("m/cadre/informasi", "routes/mobile-cadre/m.cadre.informasi.tsx"),
  route("m/cadre/anak/:anakId", "routes/mobile-cadre/m.cadre.anak.$anakId.tsx"),
  route("m/cadre/rekap", "routes/mobile-cadre/m.cadre.rekap.tsx"),
  route("puskesmas/dashboard", "routes/puskesmas.dashboard.tsx"),
  route("puskesmas/anak", "routes/puskesmas.anak.tsx"),
  route("puskesmas/anak/:anakId", "routes/puskesmas.anak.$anakId.tsx"),
  route("puskesmas/wilayah", "routes/puskesmas.wilayah.tsx"),
  route("puskesmas/kader", "routes/puskesmas.kader.tsx"),
  route("puskesmas/informasi", "routes/puskesmas.informasi.tsx"),
  route("m/puskesmas/dashboard", "routes/mobile-puskesmas/m.puskesmas.dashboard.tsx"),
  route("m/puskesmas/anak", "routes/mobile-puskesmas/m.puskesmas.anak.tsx"),
  route("m/puskesmas/informasi", "routes/mobile-puskesmas/m.puskesmas.informasi.tsx"),
  route("m/puskesmas/wilayah", "routes/mobile-puskesmas/m.puskesmas.wilayah.tsx"),
  route("m/puskesmas/kader", "routes/mobile-puskesmas/m.puskesmas.kader.tsx"),

  // Auth API Routes
  route("api/auth/login", "routes/api.auth.login.tsx"),
  route("api/auth/register", "routes/api.auth.register.tsx"),
  route("api/auth/logout", "routes/api.auth.logout.tsx"),
  route("api/auth/me", "routes/api.auth.me.tsx"),
  route("api/wilayah", "routes/api.wilayah.tsx"),

  // Dashboard API Routes
  route("api/parent/dashboard", "routes/api.parent.dashboard.tsx"),
  route("api/parent/profil-ibu", "routes/api.parent.profil-ibu.tsx"),
  route("api/parent/profil-anak", "routes/api.parent.profil-anak.tsx"),
  route("api/cadre/dashboard", "routes/api.cadre.dashboard.tsx"),
  route("api/puskesmas/dashboard", "routes/api.puskesmas.dashboard.tsx"),
] satisfies RouteConfig;
